app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'

urlpatterns=[
    path('tarun/', tarun ,name='tarun'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('hari/',hari,name='hari'),
    

]

project5/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from app1.views import *
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('h1/',h1,name='h1'),
    path('h2/',h2,name='h2'),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def h1(request):
    return render(request,"h1.html")
def h2(request):
    return render(request,"h2.html")
def tarun(request):
    return render(request,'tarun.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def hari(request):
    return render(request,'hari.html')

templates/h1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is h1 page</h1>
        <h2><a href="{% url 'h2'%}">navigate to h2</a></h2>
        
    </center>
</body>
</html>

templates/h2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is h2 page</h1>
        <h2><a href="{% url 'h1'%}">navigate to h1</a></h2>
        
    </center>
</body>
</html>

templates/hari.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is Hari's page</h1>
        <a href="{% url 'app1:tarun' %}">tarun's page</a>
        
        
    </center>
</body>
</html>

templates/tarun.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is Tarun's page</h1>
        <a href="{% url 'app2:hari' %}">hari's page</a>
        
        
    </center>
</body>
</html>